---
apiVersion: v1
kind: Service
metadata:
  name: identity-svc
  labels: 
    app: identity
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: identity
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
  labels: 
    app: order
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: order
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-svc
  labels: 
    app: catalog
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: catalog
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: basket-svc
  labels: 
    app: basket
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: basket
  type: ClusterIP
